package com.ibm.bugBts;

public enum STATUS {
	NEW, ASSIGNED, OPEN, FIXED, PENDING_RETEST, RETEST, REOPEN, VERIFIED, CLOSED, DEFERRED, DUPLICATE, REJECTED,
	NOT_A_BUG, COULD_NOT_REPRODUCE, NEED_MORE_INFO, WONT_FIX

}
